### ISSUE TITLE
Why is default Font Size variable is 1.3rem

### ISSUE THREAD

**Issue by nikhilkuyya** [jen4web/fem-getting-started-with-css#3]
Could you please correct my understanding 
- why we have set font-size : 1.3rem ( may be this value 16*1.3) why not configuring 20px/21px.
what are advantages or using rem in default font-size variable.

**Comment by jen4web** [comment]
Relative units are still best for responsive design. Here's a good article that explains why:
https://www.24a11y.com/2019/pixels-vs-relative-units-in-css-why-its-still-a-big-deal/

In general, you'll find I use:
- rem for font size and padding
- % for margin, particularly when combined with the border box model -- see https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing
- % for flex-basis or width as appropriate
- fr for grid sizing.
- px for border widths or media queries -- that's pretty much it.

**Comment by nikhilkuyya** [comment]
Accessibility behaviour
- so setting the default rem to body makes assure that all the missed with em or rem will also work.

**Comment by nikhilkuyya** [comment]
so Accessiblity is key.  
specifically it setting in body with 1.3rem acts as base responsive for all elements. if elements doesn't have any font-size override.
Thank you Jen
